<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE app-descriptor [
  <!ELEMENT app-descriptor ( dir-structure+, copy-pattern+ ) >
  <!ATTLIST app-descriptor
    update (true|false) #IMPLIED
    id CDATA #IMPLIED
    default-name CDATA #IMPLIED
  >
  <!ELEMENT dir-structure ( dir+ ) >
  <!ELEMENT dir ( #PCDATA ) >
  <!ATTLIST dir
    primary (true|false) #IMPLIED
    platform (win|unix) #IMPLIED
  >
  <!ELEMENT copy-pattern ( copy+ ) >
  <!ATTLIST copy-pattern src-root CDATA #REQUIRED >
  <!ELEMENT copy ( src-dir, src-file, dest-dir ) >
  <!ATTLIST copy
    clear-dest-dir (true|false) #IMPLIED
    recursive (true|false) #IMPLIED
    preserve-subdirs (true|false) #IMPLIED
    filter-files (true|false) #IMPLIED
    mode CDATA #IMPLIED
    primary (true|false) #IMPLIED
    platform (win|unix) #IMPLIED
    endeca-version (460|470|480|500) #IMPLIED
  >
  <!ELEMENT dest-dir ( #PCDATA ) >
  <!ELEMENT src-dir ( #PCDATA ) >
  <!ELEMENT src-file ( #PCDATA ) >
]>
<app-descriptor update="true" id="CRSApp" default-name="CRS">
  <dir-structure>
    <dir>config/import</dir>
  </dir-structure>
  <copy-pattern src-root=".">
    <copy filter-files="true" clear-dest-dir="false" preserve-subdirs="true" recursive="true">
      <src-dir>./import</src-dir>
      <src-file>*</src-file>
      <dest-dir>./config/import</dest-dir>
    </copy>
  </copy-pattern>
</app-descriptor>
<!-- @version $Id: //hosting-blueprint/B2CBlueprint/version/11.3.1/Mobile/DCS-CSR/Endeca/deploy/deploy.xml#1 $$Change: 1497274 $-->
